# https://alacritty.org/config-alacritty.html

[window]
padding = { x = 8, y = 8 }

[font]
size = 12.0

[font.normal]
family = "Roboto Mono"

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[colors.normal]
black = '#546e7a'
red = '#f07178'
green = '#c3e88d'
yellow = '#ffcb6b'
blue = '#82aaff'
magenta = '#c792ea'
cyan = '#89ddff'
white = '#eeffff'

[colors.bright]
black = '#546e7a'
red = '#f07178'
green = '#c3e88d'
yellow = '#ffcb6b'
blue = '#82aaff'
magenta = '#c792ea'
cyan = '#89ddff'
white = '#ffffff'
