# https://alacritty.org/config-alacritty.html

# live_config_reload = true

[font]
size = 12.0

[font.normal]
family = "Roboto Mono"

[colors.primary]
foreground = "#f0f0f0"
background = "#181818"

[colors.cursor]
cursor = "#ffde21"

